# Creator: djuelg @ https://github.com/djuelg
# Run via: hugo server --theme=Shapez-Theme --buildDrafts --bind="0.0.0.0"

baseurl = "http://0.0.0.0/"
title = "Gothenburg Tech Radar"
theme = "Shapez-Theme"
copyright = "Copyright (c) 2016, djuelg; all rights reserved."
[author]
    name = "robinm"
    
languageCode = "sv-SE"
MetaDataFormat = "toml"
PaginatePath = "page"
googleAnalytics = ""

[params]
    # Meta Information
    name = "Gothenburg Tech Radar"
    description = "Gothenburg Tech Radar, a monthly meetup focused on emerging technology."

    # Homepage Start-Screen, variables can be left empty, links dont start with /
    title_l1 = "Gothenburg Tech Radar"
    title_l2 = ""
    subtitle_l1 = "Meetup in Gothenburg, Sweden"
#    subtitle_l2 = "---"
#    subtitle_l3 = "Emerging technologies."
    # For these Links you need the full URL, because external links are supported
#    title_link = "http://djuelg.github.io/about/"
#    subtitle_link = ""

    # Possible values are: auto | optimizeSpeed | optimizeQuality
    start_screen_image_quality = "auto"

    # Enter links for the buttons (button one has the house sign), shouldn't be left empty
    button_1 = ""
    button_2 = "past/"
    button_3 = "about/"

    logo = "images/logo.png"
    logo_start_screen_rotation = "19"
    # This is a workaround to the original paginate param, to apply x articles per page AND sort by date
    paginate = 2
    keywords = "gothenburg tech meetup, emerging technology, technology radar"
